#!/usr/bin/env bash
# Transfer a file from a client to a server.
#
# This script accepts 4 parameters:
# 	- Path to the file to be transferred.
#	- IP of the server we want to transfer the file to
#	- Username scp connects with
#	- Path to the SSH private key that scp uses
#

if [ "$4" ] ; then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
elif [ "$3" ] ; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi