#!/usr/bin/env bash
# Install a nginx web server that listens on port 80.
#
# on  querying nginx at its root / with a GET
# request, it must returns a page that contains the string
# 'Hello World!'.
#

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!"/var/www/html/index.html
service nginx restart
