#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine it's executed on

# Use the ip command to extract active IPv4 addresses
ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | tr -d '\n' | tr ' ' '\n'
